### ISSUE TITLE
`excludeDevDependencies: true` seems pointless and time-consuming 

### ISSUE THREAD

**Issue by enapupe** [agutoli/serverless-layers#17]
I don't see the point of this. From what I understand, the existing node_modules folder will be ignored completely and will be installed using `customInstallationCommand`, which for me is `yarn -p`. Having `excludeDevDependencies` set to true will only spend computing time on something that will be package ignored. 
I was able to save 10+ seconds setting this flag to false.

**Comment by agutoli** [comment]
Hi, @enapupe. I appreciate your message. 

So, yeah. I can not use "the existing node_modules" to create AWS lambda layers, that's because it has dev dependencies as well (which is not necessary to be uploaded). So I really need to "ignore" existing node_modules, that's is correct and expected.

Therefore, `customInstallationCommand` is necessary for some cases who's someone needs to install a "production" package and your environment uses a proxy or a custom install command (again, this plugin ignores your node_modules). 

About config bellow, it's because you can ignore your existing node_modules which will not be used by serverless-layers when packing your project, so your package should be drastically smaller if compared when you remove this config:

```json
package:
  individually: false
  exclude:
    - node_modules/**
  excludeDevDependencies: true
```
Stil about "I was able to save 10+ seconds setting this flag to false", I will investigate better ". Thanks again.

**Comment by enapupe** [comment]
Sorry if I wasn't clear enough. 
My assumption is: if the layer is being generated by customInstallationCommand and node_modules is package ignored, there is no point in spending time separating what's devDeps and what not, which seems to be what that flag is doing.

FWW I have set the flag to false and it did not affect uploaded files, while it saved package time.

Hope that clears my question. Thanks for your time have a good qeekendy.

**Comment by agutoli** [comment]
Oh.. ok, yes. You probably right. I will remove it from README. This `excludeDevDependencies` is a good option when is not using `serverless-layers`.

thanks for raising that point!

**Comment by enapupe** [comment]
I see you have just changed how this was working and thus removed it from the readme, which makes sense.
However, it seems you should automatically set `excludeDevDependencies: false` as it default to true and it's pointless - as discussed

**Comment by agutoli** [comment]
Cool. I can do that. Just add one line at:
https://github.com/agutoli/serverless-layers/blob/master/src/index.js#L161

**Comment by agutoli** [comment]
Thank for your contribution.

**Comment by agutoli** [comment]
Done! Now it's setting `excludeDevDependencies = false ` automatically. 

Thank you for the suggestion!

https://github.com/agutoli/serverless-layers/blob/master/src/index.js#L166
